# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://chrisfleming.org/
title: chrisfleming.org
subtitle: my home
author: Chris Fleming
baseurl: ""
description:
  musings on photography, mapping and life
  in general.

header_pages:
 - index.html
 - blog/archives/

show_post_footers: true
collections:
  category:
    output: true
  code:
    output: true

show_social_icons: true

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #


# UI Text
text:
  pagination:
    newer: 'Newer'
    older: 'Older'
  post:
    updated:        'Updated'
    minute_read:    'minute read'
    related_posts:  'Related Posts'
  index:
    coming_soon: 'Coming soon...'
  og_locale: 'en_US'

# Octopress 2-style excerpts
excerpt_separator: "<!-- more -->"
excerpt_link: "Read on &rarr;"

# Linkblog (external-url)
linkblog:
  permalink_label: "&#8734;"
  permalink_label_feed: "&#9875; Permalink"
  linkpost:
marker: "&rarr;"


markdown: kramdown
theme: jekyll-theme-hydeout
kramdown:
  smart_quotes: ["apos", "apos", "quot", "quot"]  # Disable smart-quotes
  input: GFM
  syntax_highlighter: rouge





# If publishing to a subdirectory as in http://site.com/project set 'root: /project'
root: /chrisfleming-org-built
permalink: /:categories/:title/
# You need to have this extra permalink_custom_vars array to tell the plugin which substitutions to make
permalink_custom_vars: ['categories']

code_dir: downloads/code
category_dir: /

paginate: 10          # Posts per page on the blog index
paginate_path: "/page/:num/"       # Directory base for pagination URLs eg. /blog/page/2/

titlecase: true       # Converts page and post titles to titlecase

sass:
  style: compressed
include:
  - .htaccess
  - .nojekyll
exclude:
  - Gemfile
  - Gemfile.lock
  - script/
  - vendor/
  - LICENSE.txt
  - README.md
  - docker-compose.yml

plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Github repositories
github_user: chrisfleming
github_repo_count: 0
github_show_profile_link: true
github_skip_forks: true

# Twitter
twitter_usernane: chrisfl

# Disqus Comments
disqus.shortname: chrisfleming

# Google Analytics
google_analytics_tracking_id: UA-556965-4

jekyll-archives:
  enabled: all
  layout: archive
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/:name/'
